name: Build docker images

on:
  workflow_dispatch:
  pull_request: 
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_platform:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Make platform Docker images
            run: |
              cd docker && make build-platform
  build_XPUM:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Make xpum Docker images
            run: |
              cd docker && make build-xpum
  build_IGT:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Build igt Docker images
            run: |
              cd docker && make build-igt
